name: Deploy to Azure Web App - SQL Tutor OpenAI

on:
  push:
    branches:
      - openai-version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_openai.txt

      - name: Upload to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: sql-tutor-openai   # ← replace this with your exact app name
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
