
name: Build and Deploy SQL Tutor App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test if secret is stored
        run: |
          if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" ]; then
            echo "❌ Secret is EMPTY"
            exit 1
          else
            echo "✅ Secret is PRESENT"
          fi

      - name: Azure Login
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Build and Push Container
        run: |
          docker build -t sql-tutor-app .
          docker save sql-tutor-app | gzip > sql-tutor-app.tar.gz

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: sql-tutor-app
          package: sql-tutor-app.tar.gz
